"""
crime_categories.py
────────────────────────────────────────────────
Shared category map used by both city ETL scripts.

Maps each city's raw crime labels to one standardized
category so both SQL tables use the same vocabulary.

Add new mappings here if you find unmapped crime types
after running the ETL (they'll show up as "Other").
────────────────────────────────────────────────
"""

CRIME_CATEGORY_MAP = {

    # ── Seattle (NIBRS labels) ──────────────────────────────────────
    "LARCENY-THEFT":                        "Theft",
    "BURGLARY/BREAKING&ENTERING":           "Burglary",
    "BURGLARY":                             "Burglary",
    "MOTOR VEHICLE THEFT":                  "Vehicle Theft",
    "ROBBERY":                              "Robbery",
    "ASSAULT OFFENSES":                     "Assault",
    "AGGRAVATED ASSAULT":                   "Assault",
    "SIMPLE ASSAULT":                       "Assault",
    "INTIMIDATION":                         "Assault",
    "HOMICIDE OFFENSES":                    "Homicide",
    "MURDER & NONNEGLIGENT MANSLAUGHTER":   "Homicide",
    "NEGLIGENT MANSLAUGHTER":               "Homicide",
    "DRUG/NARCOTIC OFFENSES":               "Drugs",
    "DRUG EQUIPMENT VIOLATIONS":            "Drugs",
    "VANDALISM":                            "Vandalism",
    "DESTRUCTION/DAMAGE/VANDALISM OF PROPERTY": "Vandalism",
    "FRAUD OFFENSES":                       "Fraud",
    "COUNTERFEITING/FORGERY":               "Fraud",
    "EMBEZZLEMENT":                         "Fraud",
    "IDENTITY THEFT":                       "Fraud",
    "WIRE FRAUD":                           "Fraud",
    "TRESPASS OF REAL PROPERTY":            "Trespassing",
    "WEAPON LAW VIOLATIONS":                "Weapons",
    "SEX OFFENSES":                         "Sex Offenses",
    "RAPE":                                 "Sex Offenses",
    "SODOMY":                               "Sex Offenses",
    "SEXUAL ASSAULT WITH AN OBJECT":        "Sex Offenses",
    "FONDLING":                             "Sex Offenses",
    "INCEST":                               "Sex Offenses",
    "STATUTORY RAPE":                       "Sex Offenses",
    "ARSON":                                "Arson",
    "KIDNAPPING/ABDUCTION":                 "Kidnapping",
    "HUMAN TRAFFICKING":                    "Human Trafficking",
    "PROSTITUTION OFFENSES":                "Prostitution",
    "BRIBERY":                              "Public Corruption",
    "EXTORTION/BLACKMAIL":                  "Robbery",        # treated as coercive theft
    "STOLEN PROPERTY OFFENSES":             "Theft",
    "SHOPLIFTING":                          "Theft",
    "THEFT FROM MOTOR VEHICLE":             "Theft",
    "THEFT OF MOTOR VEHICLE PARTS":         "Theft",
    "POCKET-PICKING":                       "Theft",
    "PURSE-SNATCHING":                      "Theft",
    "THEFT FROM BUILDING":                  "Theft",
    "THEFT FROM COIN-OPERATED MACHINE":     "Theft",
    "BAD CHECKS":                           "Fraud",
    "CURFEW/LOITERING/VAGRANCY":            "Public Disorder",
    "DISORDERLY CONDUCT":                   "Public Disorder",
    "DRUNKENNESS":                          "Public Disorder",
    "FAMILY OFFENSES, NONVIOLENT":          "Domestic / Family",
    "PEEPING TOM":                          "Sex Offenses",
    "PORNOGRAPHY/OBSCENE MATERIAL":         "Sex Offenses",
    "GAMBLING OFFENSES":                    "Gambling",
    "ANIMAL CRUELTY":                       "Other",
    "NOT A CRIME":                          "Other",
    "ALL OTHER OFFENSES":                   "Other",

    # ── Chicago (Primary Type labels) ──────────────────────────────
    "THEFT":                                "Theft",
    "BURGLARY":                             "Burglary",
    "MOTOR VEHICLE THEFT":                  "Vehicle Theft",
    "ROBBERY":                              "Robbery",
    "ASSAULT":                              "Assault",
    "BATTERY":                              "Assault",          # Chicago uses Battery; maps to Assault
    "AGGRAVATED ASSAULT":                   "Assault",
    "AGGRAVATED BATTERY":                   "Assault",
    "HOMICIDE":                             "Homicide",
    "NARCOTICS":                            "Drugs",
    "OTHER NARCOTIC VIOLATION":             "Drugs",
    "CRIMINAL DAMAGE":                      "Vandalism",
    "DECEPTIVE PRACTICE":                   "Fraud",
    "CRIMINAL TRESPASS":                    "Trespassing",
    "WEAPONS VIOLATION":                    "Weapons",
    "SEX OFFENSE":                          "Sex Offenses",
    "CRIM SEXUAL ASSAULT":                  "Sex Offenses",
    "CRIMINAL SEXUAL ASSAULT":              "Sex Offenses",
    "ARSON":                                "Arson",
    "KIDNAPPING":                           "Kidnapping",
    "HUMAN TRAFFICKING":                    "Human Trafficking",
    "PROSTITUTION":                         "Prostitution",
    "OFFENSE INVOLVING CHILDREN":           "Offenses Involving Minors",
    "INTIMIDATION":                         "Assault",
    "STALKING":                             "Assault",
    "LIQUOR LAW VIOLATION":                 "Public Disorder",
    "PUBLIC PEACE VIOLATION":               "Public Disorder",
    "GAMBLING":                             "Gambling",
    "INTERFERENCE WITH PUBLIC OFFICER":     "Public Corruption",
    "OBSCENITY":                            "Sex Offenses",
    "NON-CRIMINAL":                         "Other",
    "NON - CRIMINAL":                       "Other",
    "NON-CRIMINAL (SUBJECT SPECIFIED)":     "Other",
    "OTHER OFFENSE":                        "Other",
    "CONCEALED CARRY LICENSE VIOLATION":    "Weapons",
    "RITUALISM":                            "Other",
    "DOMESTIC VIOLENCE":                    "Domestic / Family",
}